### ISSUE TITLE
removed gcs21 devices

### ISSUE THREAD

**Issue by SReich-EMI** [PI-PhysikInstrumente/PIPython#1]
Dear PI-Team,
I'm wondering, why the complete gcs21 devices are removed in the new version 2.7? I have several devices belonging to this gcs, which are no longer available with the new version? Or can they be switched to gcs3? In the changelog nothing is written about that.
I'm looking forward for an answer.

Kind regards

**Comment by Software-PhysikInstrumente** [comment]
They can be easily switched to gcs3, because the name of the syntax version changed from gcs21 to gcs3. Functions are the same, but the name has changed.

**Comment by SReich-EMI** [comment]
Thanks for this information. It is working fine!
