### ISSUE TITLE
Unzip the source code

### ISSUE THREAD

**Issue by kadykov** [PI-PhysikInstrumente/PIPython#10]
A huge part of the code of the `PIPython` package is stored in the zip-archive `PIPython/PIPython.zip`
It is excellent for saving space, but it complicates the contribution to this project, for instance making pull requests.
Is it possible to publish an unzipped version of the package?

**Comment by Software-PhysikInstrumente** [comment]
We are working on this and will let you know as soon as an updated release is available.

**Comment by Software-PhysikInstrumente** [comment]
Dear kadykov,

we would like to inform you that we will continue to publish new releases of PIPython as ZIP archive.

If you have any suggestions (bugfixes, improvements, ...) please feel free to contact us.

Thank you for your feedback

**Comment by meawoppl** [comment]
Month long review to keep zipfiles of code in the code tree...Time for a fork.
