### ISSUE TITLE
libpi_pi_gcs2.so not found

### ISSUE THREAD

**Issue by francdoc** [PI-PhysikInstrumente/PIPython#12]
Hi, I keep getting this error. I cloned this repo and ran the installation commands. Can you tell me how to get this shared object file please? Maybe I did something wrong.

```
>>> from pipython import GCSDevice
>>> pidevice = GCSDevice('C-884')
>>> pidevice.InterfaceSetupDlg()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/pipython/pidevice/common/gcsbasedevice.py", line 131, in InterfaceSetupDlg
    self.dll.InterfaceSetupDlg(key)
  File "/usr/local/lib/python3.10/dist-packages/pipython/pidevice/interfaces/gcsdll.py", line 376, in InterfaceSetupDlg
    self._id = getattr(self._handle, self._prefix + 'InterfaceSetupDlg')(key)
  File "/usr/local/lib/python3.10/dist-packages/pipython/pidevice/interfaces/gcsdll.py", line 277, in _handle
    raise IOError('%r not found' % self._dllpath)
OSError: '/home/.../PIPython/libpi_pi_gcs2.so' not found
>>> 
```

I'm running Ubuntu 22.04 LTS.

Thanks in advance

**Comment by iancynk** [comment]
Hi, I have the same issue. @francdoc how have you solved it?

**Comment by francdoc** [comment]
Yes, let me review it and I'll let you know how I solved it.

**Comment by Steffen-W** [comment]
I have the same error on Linux Mint 21.3. I have installed the package via `pip install PIPython`. What could be the problem?

**Comment by francdoc** [comment]
Hi @Steffen-W and @iancynk. 

I changed my strategy towards controlling the device. You can check out the updated approach in my project [repository](https://github.com/francdoc/PIPython/blob/testapi/samples/xycontroller.py).

First install the **PIPython package** using the next command:

`sudo pip3 install PIPython
`

Install the required Python packages:

`sudo pip3 install PyUSB PySocket PySerial
`

Now follow the next [readme](https://github.com/francdoc/PIPython/blob/testapi/readme.md) instructions to install the drivers:

1) Unzip the PI_drivers folder on a Linux PC or laptop.
2) Make the INSTALL script executable:

`
sudo chmod +x ~/PI_drivers/Linux/PI_E727-1.3.0.0-INSTALL/PI_E727/INSTALL
`

Run the INSTALL script:

`
sudo ./INSTALL
`

**Testing the Setup:**

Once you've completed the installation, try executing some of the instructions provided in the [readme](https://github.com/francdoc/PIPython/blob/testapi/readme.md).

You can also test the device control functionality by running a small [API](https://github.com/francdoc/PIPython/blob/testapi/samples/xycontroller.py#L3-L12) that I developed. This API allows the device to execute a predefined path, which is configured through a [CSV file](https://github.com/francdoc/PIPython/blob/testapi/samples/absolute_coor_2d_path.csv).

You will have to adapt [this](https://github.com/francdoc/PIPython/blob/testapi/samples/xycontroller.py#L40) line of code to the device you are using. In my case I have the P-541.2DD. Take a look at this [function](https://github.com/francdoc/PIPython/blob/testapi/samples/xycontroller.py#L52) as well, you might need to edit it according to your needs.

I'm using **Ubuntu 22.04.4 LTS**.

Hope this helps.

**Comment by Steffen-W** [comment]
Hi @francdoc, thank you very much for your explanation. Which PI_drivers zip file do you mean exactly. I can't find it anywhere. Many thanks in advance.

**Comment by fchiesad** [comment]
Hi @Steffen-W,

No problem. In my case, the drivers came on a disk with the device. Have you tried reaching out to support for help with this issue?

**Comment by francdoc** [comment]
Hi [@Steffen-W](https://github.com/Steffen-W),
No problem. In my case, the drivers came on a disk with the device. Have you tried reaching out to support for help with this issue?

I have the drivers for this [exact controller](https://www.physikinstrumente.com/en/products/controllers-and-drivers/nanopositioning-piezo-controllers/e-727x-e-727xp-digital-multi-channel-piezo-controller-412418442).

**Comment by Steffen-W** [comment]
I have added it below so that not everyone has to search for it themselves. “PI GCS2” was only required for me, the other items could be rejected. I would really like to see @Software-PhysikInstrumente  make this more user-friendly without everyone having to figure it out for themselves.
```
# sudo ./INSTALL --x86_64
Read the General Software License Agreement? [ynq]: y
Do you agree to the General Software License Agreement? [yn]: y
Install the PI GCS2 Controller x86_64 high level GCS library? [ynq]: y
```

[PI_Application_Software.zip](https://github.com/user-attachments/files/17277200/PI_Application_Software.zip)
