### ISSUE TITLE
Make PIPython avaliable in conda-forge

### ISSUE THREAD

**Issue by rhyspoulton** [PI-PhysikInstrumente/PIPython#2]
Dear PiPython developers,

Would you be interested in having PIPython available in the [conda-forge](https://conda-forge.org/)? I can facilitate this process if you didn't mind being available to test the package once it is deployed.

**Comment by SReich-EMI** [comment]
I'm not really an developer, I'm more or less only using PiPython. But I have also written more skripts arround the pure communication parts within here. For me there is no real difference installing via pip or conda. For testing I first need to get my other issue answered as I currently stuck with the older 2.6 version.

**Comment by Software-PhysikInstrumente** [comment]
We will currently only use pip and GitHub fro distribution.
