### ISSUE TITLE
Reverse an axis

### ISSUE THREAD

**Issue by josephernest** [PI-PhysikInstrumente/PIPython#5]
I noticed that one axis is reversed in my setup: when position moves from `9.000` to `9.100`, the controller moves from left to right (or right to left I don't remember!) but all I know is that it is reversed :)
Is there a command (like `RON`, `FRF`, `SVO`, etc.) in `pipython` to configure an axis to automatically reverse the direction?

Of course I could just replace `x` by `18 - x` so that 8.5 will automatically be 9.5 (symmetry with center 9.000), but I wondered if it's possible directly at API level.

**Comment by Software-PhysikInstrumente** [comment]
Hello, 
this depends on your stage and controller. I think you change a few parameters with SPA to achive this behavior, but we would not recomend this. RON, FRF, or SVO will not change the direction of positve motion, this is defined in the controller.

**Comment by Software-PhysikInstrumente** [comment]
Please let us know if you need any further support concerning this issue by opening a new issue if needed.
