### ISSUE TITLE
Error using pitools.startup with a C-863.11 controller

### ISSUE THREAD

**Issue by amichaut** [PI-PhysikInstrumente/PIPython#6]
Following the simplemove.py example, the command: `pitools.startup(pidevice, stages=STAGES, refmodes=REFMODES)` returns an error `AssertionError: argument "stages" must not to be of type "tuple"`
This error can be fixed by running `pitools.startup(pidevice, stages='M-110.1DG1', refmodes='FNL')` instead without the tuple definition for STAGES and REFMODES as defined in simplemove.py

version info:
PI PI_GCS2_DLL.dll: V3.21.0.0
PIBase: 22.16.1.0
Path: C:\ProgramData\PI\GCSTranslator\PISTAGES3.DB Version: V3.0.66.0
FW_DSP: V1.3.0.7
PIPython: 2.8.0.3

**Comment by Software-PhysikInstrumente** [comment]
This issue has been fixed and is already available in the project repository.
