### ISSUE TITLE
Open-loop operation with the E870 controller.

### ISSUE THREAD

**Issue by quantumm** [PI-PhysikInstrumente/PIPython#9]
Hi,

First of all thanks a lot for this open-source wrapper! Would be nice that all suppliers follow your example.

My comment should probably not be considered as a bug, but rather a remark on the documentation.

In my case, I have a E870 controller, which works in open-loop operation. Thus the scripts that are suggested in the README will fail, as the MOV or POS commands are not supported by my controller, which was not very encouraging at the begining of the development. It took me quite some time to understand that and I had to dig into the library documentation.

Thus, I would suggest that you remark the open-loop case in the README, or even better to notice the qHLP function that gives the available GCS commands available depending on your controller.

Thanks for this great job again ;)

**Comment by Software-PhysikInstrumente** [comment]
We are currently working on this and will inform you as soon as there is an update available.

**Comment by Software-PhysikInstrumente** [comment]
We would like to inform you that the documentation has been supplemented according to your proposal. The corresponding changes will be included in the upcoming release 2.11.x for PIPython.
Thank you for your feedback.

**Comment by quantumm** [comment]
That is great. Thanks for your work!
